plugins:
  - serverless-python-requirements
  - serverless-iam-roles-per-function
custom:
  pythonRequirements:
    slim: true
    layer: true
    dockerizePip: non-linux


service: team3-etl
frameworkVersion: '2'
provider:
  name: aws
  runtime: python3.7
  lambdaHashingVersion: 20201221
  stage: dev
  region: eu-west-1
  iam:
    role: arn:aws:iam::505617246107:role/team-3-execution-role
package:
  individually: false
  include:
    - src/team3etl/**
    - src/__init__.py
    - src/connecting_to_db.py
    - src/loading.py
    - src/sql_script.py
    - src/trail.py
    - requirements.txt
  exclude:
    - src/__pycache__/**
    - src/.pytest_cache/**
    - src/.venv/**
    - "*"
    - "*/**"
functions:
  team3-etl: 
    handler: src/team3etl/handler.handle
    timeout: 300
    layers: 
      - !Ref PythonRequirementsLambdaLayer
    events:
      - s3:
          bucket: team3testbucket2
          event: s3:ObjectCreated:*
          rules:
            - suffix: .csv

